# Generated by Django 6.0.1 on 2026-01-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sport',
            field=models.CharField(choices=[('PETANQUE', 'Pétanque'), ('GENERIC', 'Générique')], default='GENERIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='nb_players_per_team',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='nb_teams',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
