# Generated by Django 6.0.1 on 2026-01-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_description_tournament_sport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
